// HumanMessage represents a message written by the user.
// AIMessage represents a message generated by an AI node.
import { AIMessage, HumanMessage } from "@langchain/core/messages";
import { geminiModel, cohereModel, mistralModel } from "./models.service.js";
import {createAgent, providerStrategy} from 'langchain'

import {
    StateSchema,
    MessagesValue,
    ReducedValue,
    StateGraph,
    START,
    END,
    type GraphNode
} from "@langchain/langgraph";
import { z } from "zod";

// State is the shared data that moves through every graph node.
const State = new StateSchema({
    // MessagesValue automatically keeps old messages and adds new messages.
    messages: MessagesValue,

    // These values will be used later for the two competing AI solutions.
    solution_1: new ReducedValue(z.string().default(""), {
        reducer: (current, next) => next
    }),
    solution_2: new ReducedValue(z.string().default(""), {
        reducer: (current, next) => next
    }),

    // z.object() must describe the fields that are allowed in this object.
    judge_recommendation: new ReducedValue(
        z.object({
            solution_1_score: z.number(),
            solution_2_score: z.number()
        }).default({
            solution_1_score: 0,
            solution_2_score: 0
        }),
        {
            reducer: (current, next) => next
        }
    )
});

// A node receives the current state and returns the state changes.
const solutionNode: GraphNode<typeof State> = async (state: typeof State.State) => {
    const userMessage = state.messages[0];

    if (!userMessage) {
        throw new Error("No user message was provided");
    }

    const prompt = userMessage.content.toString();

    const [geminiModel_solution, cohere_solution] = await Promise.all([
        geminiModel.invoke(prompt),
        cohereModel.invoke(prompt)
    ]);

    // This message is appended to the existing messages.
    return {
        solution_1: (geminiModel_solution as any).content.toString(),
        solution_2: (cohere_solution as any).content.toString()
    };
};

const judgeNode: GraphNode<typeof State> = async (state: typeof State.State) => {
    const{solution_1, solution_2} = state;
    const judge = createAgent({
        model: geminiModel,
        tools: [],
        responseFormat: providerStrategy(z.object({
            solution_1_score: z.number().min(0).max(10),
            solution_2_score: z.number().min(0).max(10)
        }))
    })

    const judgeResponse = await judge.invoke({
        messages: [
        new HumanMessage(
            `You are a judge for a competition between two AI solutions. Please evaluate the following solutions and provide a score from 0 to 10 for each solution, where 0 is the worst and 10 is the best. The first solution is ${solution_1} and the second solution is ${solution_2}. Please provide your scores in the following format: {"solution_1_score": <score>, "solution_2_score": <score>}.`
        )
    ] 
    })

    const result = judgeResponse.structuredResponse
    return {
        judge_recommendation: {
            solution_1_score: result.solution_1_score,
            solution_2_score: result.solution_2_score
        }
    }

}

// Build the graph: START -> solutionNode -> END.
const graph = new StateGraph(State)
    .addNode("solution", solutionNode)
    .addNode("judge", judgeNode)
    .addEdge(START, "solution")
    .addEdge("solution", "judge")
    .addEdge("judge", END)
    .compile();

// This function starts the graph with the user's message.
export default async function useGraph(userMessage: string) {
    const result = await (graph as any).invoke({
        messages: [new HumanMessage(userMessage)]
    });

    // Return the answers stored by the solution node.
    return {
        solution_1: result.solution_1,
        solution_2: result.solution_2,
        messages: result.messages
    };
}
