import {StateGraph, StateSchema, type GraphNode, START, END } from "@langchain/langgraph"
import {geminiModel, mistralModel, cohereModel, groqModel} from "./models.ai.js"
import z from "zod"
import {createAgent, HumanMessage, providerStrategy, toolStrategy} from 'langchain'


const state =  new StateSchema({
    problem: z.string().default(""),
    solution_1: z.string().default(""),
    solution_2: z.string().default(""),
    judge: z.object({
        solution_1_score: z.number().default(0),
        solution_2_score: z.number().default(0),
        solution_1_feedback: z.string().default(""),
        solution_2_feedback: z.string().default(""),
    })
})

const solutionNode: GraphNode<typeof state> = async (state) => {
    const [cohereResponse, groqResponse] = await Promise.all([
        cohereModel.invoke(state.problem),
        groqModel.invoke(state.problem),
    ])
    
    return{
        solution_1: cohereResponse.text,
        solution_2: groqResponse.text,
    }

}

const judgeNode: GraphNode <typeof state> = async (state) => {
    const {problem, solution_1, solution_2} = state


    const judge = createAgent({
        model: geminiModel,
        responseFormat: providerStrategy(
            z.object({
                solution_1_score: z.number().min(0).max(10).default(0),
                solution_2_score: z.number().min(0).max(10).default(0),
                solution_1_feedback: z.string(),
                solution_2_feedback: z.string()
            })
        ),
        systemPrompt: `You are a judge tasked with evaluating two solutions generated by differertn AI models. Please provide a score out of 10 for each solution, along with your reasoning of the scores`
        
    })

    const judgeResponse = await judge.invoke({
        messages: [
            new HumanMessage(`
                    Problem: ${problem}
                    Solution_1: ${solution_1}
                    Solutiin_2: ${solution_2}
                    Please evaluate the solutions and provide the scores and reasoning!
                `)
        ]
    })

    const {
        solution_1_score,
        solution_2_score,
        solution_1_feedback,
        solution_2_feedback
    } = judgeResponse.structuredResponse
    
    return{
        judge: {
            solution_1_score,
            solution_2_score,
            solution_1_feedback,
            solution_2_feedback
        }
    }
}

const graph = new StateGraph(state)
    .addNode("solution", solutionNode)
    .addNode("judge_node", judgeNode)
    .addEdge(START, "solution")
    .addEdge("solution", "judge_node")
    .addEdge("judge_node", END)
    .compile()


export default async function startGraph(problem: string){
    const response = await graph.invoke({
        problem: problem
    })

    return response
}