import { StateGraph, StateSchema, START, END } from "@langchain/langgraph"
import { groqModel, cohereModel } from "./models.ai.js"
import { createAgent, HumanMessage, providerStrategy } from 'langchain'
import { z } from "zod/v4"


// Each field is written SEPARATELY (flat). No nested object with one big .default({})
// because zod v4 + LangGraph break on that, and it was crashing the server (the 500 error).
const state = new StateSchema({
    problem: z.string().default(""),
    solution_1: z.string().default(""),
    solution_2: z.string().default(""),
    solution_1_score: z.number().default(0),
    solution_2_score: z.number().default(0),
    solution_1_feedback: z.string().default(""),
    solution_2_feedback: z.string().default(""),
    winner: z.string().default(""),
})

const solutionNode = async (state) => {
    const [cohereResponse, groqResponse] = await Promise.all([
        cohereModel.invoke(state.problem),
        groqModel.invoke(state.problem),
    ])

    return {
        solution_1: cohereResponse.text,
        solution_2: groqResponse.text,
    }
}

const judgeNode = async (state) => {
    const { problem, solution_1, solution_2 } = state

    // NOTE: Groq is both a fighter AND the judge (its free tier is the most generous).
    // Gemini free tier dies after 20 req/min, Mistral was giving 429 too.
    const judge = createAgent({
        model: groqModel,
        responseFormat: providerStrategy(
            z.object({
                solution_1_score: z.number().min(0).max(10),
                solution_2_score: z.number().min(0).max(10),
                solution_1_feedback: z.string(),
                solution_2_feedback: z.string(),
            })
        ),
        systemPrompt: `You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning of the scores`
    })

    const judgeResponse = await judge.invoke({
        messages: [
            new HumanMessage(`
                    Problem: ${problem}
                    Solution_1: ${solution_1}
                    Solution_2: ${solution_2}
                    Please evaluate the solutions and provide the scores and reasoning!
                `)
        ]
    })

    const {
        solution_1_score = 0,
        solution_2_score = 0,
        solution_1_feedback = "",
        solution_2_feedback = ""
    } = judgeResponse.structuredResponse ?? {}

    const winner =
        solution_1_score > solution_2_score ? "solution_1" :
        solution_2_score > solution_1_score ? "solution_2" : "tie"

    return {
        solution_1_score,
        solution_2_score,
        solution_1_feedback,
        solution_2_feedback,
        winner
    }
}

const graph = new StateGraph(state)
    .addNode("solution", solutionNode)
    .addNode("judge_node", judgeNode)
    .addEdge(START, "solution")
    .addEdge("solution", "judge_node")
    .addEdge("judge_node", END)
    .compile()


export default async function startGraph(problem: string) {
    const response = await graph.invoke({
        problem: problem
    })

    // Frontend expects a `judge` object, so we build it back from the flat fields
    return {
        solution_1: response.solution_1,
        solution_2: response.solution_2,
        judge: {
            solution_1_score: response.solution_1_score,
            solution_2_score: response.solution_2_score,
            solution_1_feedback: response.solution_1_feedback,
            solution_2_feedback: response.solution_2_feedback,
            winner: response.winner,
        },
    }
}
